<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="questionnaire" nsURI="http://www.example.org/questionnaire"
    nsPrefix="questionnaire">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Questionnaire">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="QuestionDifficulteValide"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="QuestionDifficulteValide" value="&#xA;            self.questions->forAll(q | q.difficulte >= 1 and q.difficulte &lt;= 5)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="peutRevenirEnArriere" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" upperBound="-1"
        eType="#//Question" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etiquettes" upperBound="-1"
        eType="#//Etiquette" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="DifficulteValide PropositionsMinimum ReponseCorrecteMinimum"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="DifficulteValide" value="&#xA;            self.difficulte >= 1 and self.difficulte &lt;= 5"/>
      <details key="PropositionsMinimum" value="&#xA;            self.propositions->size() >= 2"/>
      <details key="ReponseCorrecteMinimum" value="&#xA;            self.reponses->size() >= 1"/>
    </eAnnotations>
    <eOperations name="testerReponse" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intitule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulte" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeDuChoix" eType="#//TypeChoix"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propositions" lowerBound="2"
        upperBound="-1" eType="#//Proposition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reponses" lowerBound="1"
        upperBound="-1" eType="#//Proposition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etiquettes" upperBound="-1"
        eType="#//Etiquette" eOpposite="#//Etiquette/questions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Etiquette">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="EtiquetteQuestion"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="EtiquetteQuestion" value="&#xA;            self.questions.etiquettes->size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" upperBound="-1"
        eType="#//Question" eOpposite="#//Question/etiquettes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etiquettes" lowerBound="1"
        upperBound="-1" eType="#//Etiquette"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeChoix">
    <eLiterals name="CHOIX_UNIQUE"/>
    <eLiterals name="CHOIX_MULTIPLE" value="1"/>
  </eClassifiers>
</ecore:EPackage>
